export const USER_LOGIN = `USER/LOGIN`;
export const USER_LOGOUT = `USER/LOGOUT`;
export const USER_SET_NAME = `USER/SET_NAME`;

export const MESSAGE_INIT_CONNECTION = `MESSAGE/INIT_CONNECTION`;
export const MESSAGE_SEND = `MESSAGE/SEND`;
export const MESSAGE_SELECT = `MESSAGE/SELECT`;
export const MESSAGE_SET_RIGHT = `MESSAGE/SET_RIGHT`;
export const MESSAGE_NEW_MESSAGE = `MESSAGE/NEW_MESSAGE`;

export const GAME_TOGGLE_RULES = `GAME/TOGGLE_RULES`;
export const GAME_TOGGLE_START = `GAME/TOGGLE_START`;
export const GAME_SET_JUST_LOGGED = `GAME/SET_JUST_LOGGED`;
